### ISSUE TITLE
Does not update prop values

### ISSUE THREAD

**Issue by cihad** [privatenumber/vue-vnode-syringe#117]
Although I changed the value of number where the `<vnode-syring>` is used, the expression in the component does not change.

For example:

[https://codesandbox.io/s/not-affected-vnode-syring-4830t?file=/src/components/AppHeader.vue](https://codesandbox.io/s/not-affected-vnode-syring-4830t?file=/src/components/AppHeader.vue)

**Comment by privatenumber** [comment]
Nice catch @cihad !

Thanks for providing a reproduction. I was able to reproduce it locally and add it as a test.

Fix coming soon.

**Comment by privatenumber** [comment]
I forked and updated the codesandbox to use 3.0.0 and can confirm it works expectedly:
https://codesandbox.io/s/not-affected-vnode-syring-forked-d9hnn

**Comment by cihad** [comment]
Thanks. Eveything was perfect.

**Comment by cihad** [comment]
Wait a minute! Because if slot have 2 and more components, only first component is affected.

https://codesandbox.io/s/not-affected-vnode-syring-forked-m4the?file=/src/App.vue
