### ISSUE TITLE
It doesn't work prop reactivity if slot has multiple components

### ISSUE THREAD

**Issue by cihad** [privatenumber/vue-vnode-syringe#140]
For example: https://codesandbox.io/s/not-affected-vnode-syring-forked-m4the?file=/src/App.vue

**Comment by cihad** [comment]
Probably the solution is here: [src/utils.js#getPropsData](https://github.com/privatenumber/vue-vnode-syringe/blob/develop/src/utils.js#L98)

**Comment by privatenumber** [comment]
Verified this is a bug. Thanks for reporting!

Will look into a fix soon.

**Comment by privatenumber** [comment]
@cihad

This was released in v3.1.1!

Thanks again for reporting

**Comment by cihad** [comment]
thanks again me too.
